version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./:/code
    ports:
      - "${APP_PORT}:5000"
    links:
      - postgresql
    depends_on:
      - postgresql
    tty: true
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://127.0.0.1:5000/api/ || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 5

  postgresql:
    image: postgres:9.5
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
      POSTGRES_HOST: ${POSTGRESQL_HOST}
      PGDATA: /var/lib/postgresql/9.6/main
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
